<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <AssemblyName>StrikeLauncher</AssemblyName>
    <RootNamespace>StrikeLauncher</RootNamespace>
    <Product>Strike Launcher</Product>
    <Company>Age of Clones - Strike Platoon</Company>
    <Version>0.1.0</Version>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
    <PackageReference Include="Velopack" Version="0.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="steam_appid.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="steam_api64.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="config\default-config.json" CopyToOutputDirectory="PreserveNewest" />
    <None Remove="Assets\logo.png" />
    <None Remove="Assets\app.ico" />
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

</Project>
